#!/bin/bash

build_param=$1

if [ "$build_param" == "--build" ]; then
  docker-compose -p catapult-service-bootstrap -f cmds/docker/nemgen-test.yml up --build
else
  docker-compose -p catapult-service-bootstrap -f cmds/docker/nemgen-test.yml up
fi
