#!/bin/bash

build_param=$1

if [ "$build_param" == "--build" ]; then
  docker-compose -p catapult-service-bootstrap -f cmds/docker/docker-compose-setup-network.yml up --build
else
  docker-compose -p catapult-service-bootstrap -f cmds/docker/docker-compose-setup-network.yml up
fi
